### PR TITLE
CAP-321: Fork and fix mongoriver

### PR DESCRIPTION
**Pull request by faustus7**
This pull forks and fixes mongoriver for use with Mongo 2.0.

### CODE REVIEW

**Comment by faustus7** [comment]
I have CI rigged up for this repo (https://ci.yesware.com/viewType.html?buildTypeId=Gems_MongoRiver_MongoRiver&branch_Gems_MongoRiver=1&tab=buildTypeStatusDiv), but I am not currently seeing the integration on the GitHub side. Ideas?

**Review by kwong-yw — APPROVED** [review]
LGTM once CI is green

**Comment by faustus7** [comment]
Thanks for the review, and the help in getting CI running right!

**Comment by gurpreet-shah** [comment]
lgtm

**Pull request merged**
