### PR TITLE
CAP-321: Fix outlet method nomenclature

### PR DESCRIPTION
**Pull request by faustus7**
This pull fixes renamed methods introduced in the last pull.

### CODE REVIEW

**Review by sebastianfairchild — APPROVED** [review]

**Comment by gurpreet-shah** [comment]
Why is this required?

**Comment by faustus7** [comment]
> Why is this required?

The outlet names needed to be restored to their original names, since they were erroneously renamed in the last pull. Instead of a revert of the whole pull it made more sense to do a patch fix.

**Comment by faustus7** [comment]
> > Why is this required?
> 
> The outlet names needed to be restored to their original names, since they were erroneously renamed in the last pull. Instead of a revert of the whole pull it made more sense to do a patch fix.

Furthermore, we need this as part of the `simon-says` mongoid migration.

**Review by gurpreet-shah — APPROVED** [review]

**Comment by faustus7** [comment]
Thanks!

**Pull request merged**
